/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmenrolmentsystem;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 
 *
 * @author User
 */
public class studentOperate extends javax.swing.JFrame {
    javadbconnection jdb=new javadbconnection(); 
    String url="jdbc:mysql://localhost:3306/nsbmenrolsystem"; //access database
    String username="root";
    String password="";
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form studentOperate
     */
    public studentOperate() {
        initComponents();
    }
    public studentOperate(String uname) {
        initComponents();
        tuser.setText(uname);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tuser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Student Portal");

        tuser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Logged user");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tuser, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(tuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("Subjects");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton4.setText("Result");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user=tuser.getText();
        if(user.charAt(0)=='U'){
            try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,faculty,sname,regMonth from undergraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    String dbname=rs.getString("sname");
                    String dbfac=rs.getString("faculty");
                    String dbmonth=rs.getString("regMonth");
                    if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("February")){
                        Payment1 p1=new Payment1();
                        p1.setVisible(true);
                        this.dispose();
                    }else if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("July")){
                        Payment2 p2=new Payment2();
                        p2.setVisible(true);
                        this.dispose();
                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }else if(user.charAt(0)=='P'){
            try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,faculty,name,rmonth from postgraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    String dbname=rs.getString("name");
                    String dbfac=rs.getString("faculty");
                    String dbmonth=rs.getString("rmonth");
                    if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("February")){
                        
                    }else if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("July")){
                        
                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String user=tuser.getText();
        System.out.println(user);
        if(user.charAt(0)=='U'){
             System.out.println(true);
             try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,sname,faculty,nic,gender,dob,pno,email,address from undergraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    String dbname=rs.getString("sname");
                    System.out.println(dbname);
                    String dbfaculty=rs.getString("faculty");
                    String dbnic=rs.getString("nic");
                    String dbgender=rs.getString("gender");
                    String dbdob=rs.getString("dob");
                    Integer dbpno=Integer.parseInt(rs.getString("pno"));
                    String dbemail=rs.getString("email");
                    String dbaddress=rs.getString("address");
                    if(dbusername.equals(user)){
                        studentprofile stp=new studentprofile(dbname,dbfaculty,dbgender,dbdob,dbnic,dbpno,dbemail,dbaddress);
                        stp.setVisible(true);
                        this.dispose();
                    }
                }
            }catch(ClassNotFoundException | NumberFormatException | SQLException e){
                System.out.println(e);
            }
        }else if(user.charAt(0)=='P'){
             System.out.println(true);
             try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,name,faculty,nic,gender,dob,pno,email,address from postgraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    String dbname=rs.getString("name");
                    System.out.println(dbname);
                    String dbfaculty=rs.getString("faculty");
                    String dbnic=rs.getString("nic");
                    String dbgender=rs.getString("gender");
                    String dbdob=rs.getString("dob");
                    Integer dbpno=Integer.parseInt(rs.getString("pno"));
                    String dbemail=rs.getString("email");
                    String dbaddress=rs.getString("address");
                    if(dbusername.equals(user)){
                        pstudentprofile stp=new pstudentprofile(dbname,dbfaculty,dbgender,dbdob,dbnic,dbpno,dbemail,dbaddress);
                        stp.setVisible(true);
                        this.dispose();
                    }
                }
            }catch(ClassNotFoundException | NumberFormatException | SQLException e){
                System.out.println(e);
            }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user=tuser.getText();
        if(user.charAt(0)=='U'){
            try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,faculty,sname,regMonth from undergraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    System.out.println(dbusername);
                    String dbname=rs.getString("sname");
                    String dbfac=rs.getString("faculty");
                    System.out.println(dbfac);
                    String dbmonth=rs.getString("regMonth");
                    System.out.println(dbmonth);
                    if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("February")){
                        csubjectSelection_12 s=new csubjectSelection_12(user);
                        s.setVisible(true);
                        this.dispose();
                    }else if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("July")){
                        System.out.println(true);
                        csubjectSelection_11 s=new csubjectSelection_11(user);
                        s.setVisible(true);
                        this.dispose();
                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }else if(user.charAt(0)=='P'){
            System.out.println("yes");
            try{
                Class.forName("com.mysql.jdbc.Driver"); //load and register jdbc driver
                conn=(Connection)DriverManager.getConnection(url,username,password);
                String query="select username,faculty,name,rmonth from postgraduate";
                pst=conn.prepareStatement(query);
                rs=pst.executeQuery();
                while(rs.next()){
                    String dbusername=rs.getString("username");
                    String dbname=rs.getString("name");
                    String dbfac=rs.getString("faculty");
                    String dbmonth=rs.getString("rmonth");

                    if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("February")){
                        pcsubjectSelection_12 s=new pcsubjectSelection_12();
                        s.setVisible(true);
                    }else if(dbfac.equals("School Of Computing")&&dbusername.equals(user)&&dbmonth.equals("July")){
                        System.out.println(true);
                        pcsubjectSelection_11 s=new pcsubjectSelection_11();
                        s.setVisible(true);
                        this.dispose();
                    }
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentOperate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentOperate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentOperate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentOperate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentOperate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tuser;
    // End of variables declaration//GEN-END:variables
}
